# permissions for end users to edit certwatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certwatcher-editor-role
rules:
- apiGroups:
  - certwatch.morimoto.net.br
  resources:
  - certwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certwatch.morimoto.net.br
  resources:
  - certwatchers/status
  verbs:
  - get
