apiVersion: v1
entries:
  cert-watch:
  - apiVersion: v2
    appVersion: latest
    created: "2021-09-28T22:09:10.216898227-03:00"
    description: Watch and react to changes in Kubernetes TLS Secrets
    digest: d147ce214c8758f0bce9ea629172fbaa1f99591ae86521a136c757946a749bcd
    name: cert-watch
    type: application
    urls:
    - cert-watch-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: latest
    created: "2021-09-28T22:09:10.213759584-03:00"
    description: Watch and react to changes in Kubernetes TLS Secrets
    digest: 281991f3097e586024e90f24304f66c58cddbb26e53a12d4b5a18a49933983bf
    name: cert-watch
    type: application
    urls:
    - cert-watch-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: latest
    created: "2021-09-28T22:09:10.210731803-03:00"
    description: Watch and react to changes in Kubernetes TLS Secrets
    digest: 0e10d28d20fbd9b926739150286a2303793b6c9cec53a0335e7594ebd6597e62
    name: cert-watch
    type: application
    urls:
    - cert-watch-0.1.0.tgz
    version: 0.1.0
generated: "2021-09-28T22:09:10.207863752-03:00"
